### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by SachinBhankhar** [kotlincodes/image_picker_gallery_camera#10]

**Comment by luoxufeiyan** [comment]
Hi @SachinBhankhar , the code in the master branch supports null-safety. I'm using this git repo in the pubspec file and it works.

```yaml
  image_picker_gallery_camera: 
    git:
      url: git://github.com/kotlincodes/image_picker_gallery_camera.git
      ref: master
```

Hope this helps.
